services:
  - type: web
    name: anon-chat-web
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: anon-chat-db
          property: connectionString

databases:
  - name: anon-chat-db
    plan: free

 
